/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmartsheetentityUpdateRecordsRequest 更新指定表格和子表中的一到多条记录请求
type SmartsheetentityUpdateRecordsRequest struct {
	Records []SmartsheetentityCommonRecord `json:"records,omitempty"`
}

// NewSmartsheetentityUpdateRecordsRequest instantiates a new SmartsheetentityUpdateRecordsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartsheetentityUpdateRecordsRequest() *SmartsheetentityUpdateRecordsRequest {
	this := SmartsheetentityUpdateRecordsRequest{}
	return &this
}

// NewSmartsheetentityUpdateRecordsRequestWithDefaults instantiates a new SmartsheetentityUpdateRecordsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartsheetentityUpdateRecordsRequestWithDefaults() *SmartsheetentityUpdateRecordsRequest {
	this := SmartsheetentityUpdateRecordsRequest{}
	return &this
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *SmartsheetentityUpdateRecordsRequest) GetRecords() []SmartsheetentityCommonRecord {
	if o == nil || o.Records == nil {
		var ret []SmartsheetentityCommonRecord
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityUpdateRecordsRequest) GetRecordsOk() ([]SmartsheetentityCommonRecord, bool) {
	if o == nil || o.Records == nil {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *SmartsheetentityUpdateRecordsRequest) HasRecords() bool {
	if o != nil && o.Records != nil {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []SmartsheetentityCommonRecord and assigns it to the Records field.
func (o *SmartsheetentityUpdateRecordsRequest) SetRecords(v []SmartsheetentityCommonRecord) {
	o.Records = v
}

func (o SmartsheetentityUpdateRecordsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Records != nil {
		toSerialize["records"] = o.Records
	}
	return json.Marshal(toSerialize)
}

type NullableSmartsheetentityUpdateRecordsRequest struct {
	value *SmartsheetentityUpdateRecordsRequest
	isSet bool
}

func (v NullableSmartsheetentityUpdateRecordsRequest) Get() *SmartsheetentityUpdateRecordsRequest {
	return v.value
}

func (v *NullableSmartsheetentityUpdateRecordsRequest) Set(val *SmartsheetentityUpdateRecordsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartsheetentityUpdateRecordsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartsheetentityUpdateRecordsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartsheetentityUpdateRecordsRequest(val *SmartsheetentityUpdateRecordsRequest) *NullableSmartsheetentityUpdateRecordsRequest {
	return &NullableSmartsheetentityUpdateRecordsRequest{value: val, isSet: true}
}

func (v NullableSmartsheetentityUpdateRecordsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartsheetentityUpdateRecordsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


