/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmartsheetDeleteFieldsRequest 删除字段请求
type SmartsheetDeleteFieldsRequest struct {
	FieldIDs []string `json:"fieldIDs,omitempty"`
}

// NewSmartsheetDeleteFieldsRequest instantiates a new SmartsheetDeleteFieldsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartsheetDeleteFieldsRequest() *SmartsheetDeleteFieldsRequest {
	this := SmartsheetDeleteFieldsRequest{}
	return &this
}

// NewSmartsheetDeleteFieldsRequestWithDefaults instantiates a new SmartsheetDeleteFieldsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartsheetDeleteFieldsRequestWithDefaults() *SmartsheetDeleteFieldsRequest {
	this := SmartsheetDeleteFieldsRequest{}
	return &this
}

// GetFieldIDs returns the FieldIDs field value if set, zero value otherwise.
func (o *SmartsheetDeleteFieldsRequest) GetFieldIDs() []string {
	if o == nil || o.FieldIDs == nil {
		var ret []string
		return ret
	}
	return o.FieldIDs
}

// GetFieldIDsOk returns a tuple with the FieldIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetDeleteFieldsRequest) GetFieldIDsOk() ([]string, bool) {
	if o == nil || o.FieldIDs == nil {
		return nil, false
	}
	return o.FieldIDs, true
}

// HasFieldIDs returns a boolean if a field has been set.
func (o *SmartsheetDeleteFieldsRequest) HasFieldIDs() bool {
	if o != nil && o.FieldIDs != nil {
		return true
	}

	return false
}

// SetFieldIDs gets a reference to the given []string and assigns it to the FieldIDs field.
func (o *SmartsheetDeleteFieldsRequest) SetFieldIDs(v []string) {
	o.FieldIDs = v
}

func (o SmartsheetDeleteFieldsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.FieldIDs != nil {
		toSerialize["fieldIDs"] = o.FieldIDs
	}
	return json.Marshal(toSerialize)
}

type NullableSmartsheetDeleteFieldsRequest struct {
	value *SmartsheetDeleteFieldsRequest
	isSet bool
}

func (v NullableSmartsheetDeleteFieldsRequest) Get() *SmartsheetDeleteFieldsRequest {
	return v.value
}

func (v *NullableSmartsheetDeleteFieldsRequest) Set(val *SmartsheetDeleteFieldsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartsheetDeleteFieldsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartsheetDeleteFieldsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartsheetDeleteFieldsRequest(val *SmartsheetDeleteFieldsRequest) *NullableSmartsheetDeleteFieldsRequest {
	return &NullableSmartsheetDeleteFieldsRequest{value: val, isSet: true}
}

func (v NullableSmartsheetDeleteFieldsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartsheetDeleteFieldsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


