/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com/open/wiki); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmartsheetRecord struct for SmartsheetRecord
type SmartsheetRecord struct {
	RecordID *string `json:"recordID,omitempty"`
	CreateTime *int64 `json:"createTime,omitempty"`
	UpdateTime *int64 `json:"updateTime,omitempty"`
	Values *map[string]interface{} `json:"values,omitempty"`
}

// NewSmartsheetRecord instantiates a new SmartsheetRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartsheetRecord() *SmartsheetRecord {
	this := SmartsheetRecord{}
	return &this
}

// NewSmartsheetRecordWithDefaults instantiates a new SmartsheetRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartsheetRecordWithDefaults() *SmartsheetRecord {
	this := SmartsheetRecord{}
	return &this
}

// GetRecordID returns the RecordID field value if set, zero value otherwise.
func (o *SmartsheetRecord) GetRecordID() string {
	if o == nil || o.RecordID == nil {
		var ret string
		return ret
	}
	return *o.RecordID
}

// GetRecordIDOk returns a tuple with the RecordID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetRecord) GetRecordIDOk() (*string, bool) {
	if o == nil || o.RecordID == nil {
		return nil, false
	}
	return o.RecordID, true
}

// HasRecordID returns a boolean if a field has been set.
func (o *SmartsheetRecord) HasRecordID() bool {
	if o != nil && o.RecordID != nil {
		return true
	}

	return false
}

// SetRecordID gets a reference to the given string and assigns it to the RecordID field.
func (o *SmartsheetRecord) SetRecordID(v string) {
	o.RecordID = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *SmartsheetRecord) GetCreateTime() int64 {
	if o == nil || o.CreateTime == nil {
		var ret int64
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetRecord) GetCreateTimeOk() (*int64, bool) {
	if o == nil || o.CreateTime == nil {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *SmartsheetRecord) HasCreateTime() bool {
	if o != nil && o.CreateTime != nil {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given int64 and assigns it to the CreateTime field.
func (o *SmartsheetRecord) SetCreateTime(v int64) {
	o.CreateTime = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *SmartsheetRecord) GetUpdateTime() int64 {
	if o == nil || o.UpdateTime == nil {
		var ret int64
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetRecord) GetUpdateTimeOk() (*int64, bool) {
	if o == nil || o.UpdateTime == nil {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *SmartsheetRecord) HasUpdateTime() bool {
	if o != nil && o.UpdateTime != nil {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given int64 and assigns it to the UpdateTime field.
func (o *SmartsheetRecord) SetUpdateTime(v int64) {
	o.UpdateTime = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *SmartsheetRecord) GetValues() map[string]interface{} {
	if o == nil || o.Values == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetRecord) GetValuesOk() (*map[string]interface{}, bool) {
	if o == nil || o.Values == nil {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *SmartsheetRecord) HasValues() bool {
	if o != nil && o.Values != nil {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]interface{} and assigns it to the Values field.
func (o *SmartsheetRecord) SetValues(v map[string]interface{}) {
	o.Values = &v
}

func (o SmartsheetRecord) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RecordID != nil {
		toSerialize["recordID"] = o.RecordID
	}
	if o.CreateTime != nil {
		toSerialize["createTime"] = o.CreateTime
	}
	if o.UpdateTime != nil {
		toSerialize["updateTime"] = o.UpdateTime
	}
	if o.Values != nil {
		toSerialize["values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableSmartsheetRecord struct {
	value *SmartsheetRecord
	isSet bool
}

func (v NullableSmartsheetRecord) Get() *SmartsheetRecord {
	return v.value
}

func (v *NullableSmartsheetRecord) Set(val *SmartsheetRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartsheetRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartsheetRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartsheetRecord(val *SmartsheetRecord) *NullableSmartsheetRecord {
	return &NullableSmartsheetRecord{value: val, isSet: true}
}

func (v NullableSmartsheetRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartsheetRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


