/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmartsheetUpdateRecordsResponse 更新指定表格和子表中的一到多条记录回包
type SmartsheetUpdateRecordsResponse struct {
	Records []SmartsheetCommonRecord `json:"records,omitempty"`
}

// NewSmartsheetUpdateRecordsResponse instantiates a new SmartsheetUpdateRecordsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartsheetUpdateRecordsResponse() *SmartsheetUpdateRecordsResponse {
	this := SmartsheetUpdateRecordsResponse{}
	return &this
}

// NewSmartsheetUpdateRecordsResponseWithDefaults instantiates a new SmartsheetUpdateRecordsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartsheetUpdateRecordsResponseWithDefaults() *SmartsheetUpdateRecordsResponse {
	this := SmartsheetUpdateRecordsResponse{}
	return &this
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *SmartsheetUpdateRecordsResponse) GetRecords() []SmartsheetCommonRecord {
	if o == nil || o.Records == nil {
		var ret []SmartsheetCommonRecord
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetUpdateRecordsResponse) GetRecordsOk() ([]SmartsheetCommonRecord, bool) {
	if o == nil || o.Records == nil {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *SmartsheetUpdateRecordsResponse) HasRecords() bool {
	if o != nil && o.Records != nil {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []SmartsheetCommonRecord and assigns it to the Records field.
func (o *SmartsheetUpdateRecordsResponse) SetRecords(v []SmartsheetCommonRecord) {
	o.Records = v
}

func (o SmartsheetUpdateRecordsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Records != nil {
		toSerialize["records"] = o.Records
	}
	return json.Marshal(toSerialize)
}

type NullableSmartsheetUpdateRecordsResponse struct {
	value *SmartsheetUpdateRecordsResponse
	isSet bool
}

func (v NullableSmartsheetUpdateRecordsResponse) Get() *SmartsheetUpdateRecordsResponse {
	return v.value
}

func (v *NullableSmartsheetUpdateRecordsResponse) Set(val *SmartsheetUpdateRecordsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartsheetUpdateRecordsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartsheetUpdateRecordsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartsheetUpdateRecordsResponse(val *SmartsheetUpdateRecordsResponse) *NullableSmartsheetUpdateRecordsResponse {
	return &NullableSmartsheetUpdateRecordsResponse{value: val, isSet: true}
}

func (v NullableSmartsheetUpdateRecordsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartsheetUpdateRecordsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


