/*
 * Tencent Docs SDK
 *
 * This is tencent docs editorapi sdk
 *
 * API version: 0.1.0
 * Contact: tencentdocs@tencent.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InsertWebBlockRequest struct {
	Location *Location `json:"location"`
	// 插件 ID
	AddonID string `json:"addonID"`
	// 文档插件元素的唯一ID(6位的数字小写字母组合)
	AnchorID string `json:"anchorID"`
	// 展示文本
	DisplayText string `json:"displayText,omitempty"`
	// 插件宽度，单位为 emu
	Width int32 `json:"width,omitempty"`
	// 插件高度，单位为 emu
	Height int32 `json:"height,omitempty"`
	// 原始URL
	OriginalURL string `json:"originalURL"`
	// 插件展示的URL
	EmbedURL string `json:"embedURL"`
	AddonType int32 `json:"addonType"`
	// 插件扩展字段
	ExtraData string `json:"extraData,omitempty"`
	// 锁定宽高比, Default: true
	LockAspectRatio bool `json:"lockAspectRatio,omitempty"`
}
