/*
 * Tencent Docs SDK
 *
 * This is tencent docs editorapi sdk
 *
 * API version: 0.1.0
 * Contact: tencentdocs@tencent.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InsertTextRequest struct {
	Text string `json:"text"`
	Location *Location `json:"location"`
}
