/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmartsheetentityGetViewsResponse 获取指定表格指定子表中的所有视图回包
type SmartsheetentityGetViewsResponse struct {
	Total *int32 `json:"total,omitempty"`
	HasMore *bool `json:"hasMore,omitempty"`
	Next *int32 `json:"next,omitempty"`
	Views []SmartsheetentityView `json:"views,omitempty"`
}

// NewSmartsheetentityGetViewsResponse instantiates a new SmartsheetentityGetViewsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartsheetentityGetViewsResponse() *SmartsheetentityGetViewsResponse {
	this := SmartsheetentityGetViewsResponse{}
	return &this
}

// NewSmartsheetentityGetViewsResponseWithDefaults instantiates a new SmartsheetentityGetViewsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartsheetentityGetViewsResponseWithDefaults() *SmartsheetentityGetViewsResponse {
	this := SmartsheetentityGetViewsResponse{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SmartsheetentityGetViewsResponse) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityGetViewsResponse) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SmartsheetentityGetViewsResponse) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *SmartsheetentityGetViewsResponse) SetTotal(v int32) {
	o.Total = &v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *SmartsheetentityGetViewsResponse) GetHasMore() bool {
	if o == nil || o.HasMore == nil {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityGetViewsResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil || o.HasMore == nil {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *SmartsheetentityGetViewsResponse) HasHasMore() bool {
	if o != nil && o.HasMore != nil {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *SmartsheetentityGetViewsResponse) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *SmartsheetentityGetViewsResponse) GetNext() int32 {
	if o == nil || o.Next == nil {
		var ret int32
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityGetViewsResponse) GetNextOk() (*int32, bool) {
	if o == nil || o.Next == nil {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *SmartsheetentityGetViewsResponse) HasNext() bool {
	if o != nil && o.Next != nil {
		return true
	}

	return false
}

// SetNext gets a reference to the given int32 and assigns it to the Next field.
func (o *SmartsheetentityGetViewsResponse) SetNext(v int32) {
	o.Next = &v
}

// GetViews returns the Views field value if set, zero value otherwise.
func (o *SmartsheetentityGetViewsResponse) GetViews() []SmartsheetentityView {
	if o == nil || o.Views == nil {
		var ret []SmartsheetentityView
		return ret
	}
	return o.Views
}

// GetViewsOk returns a tuple with the Views field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityGetViewsResponse) GetViewsOk() ([]SmartsheetentityView, bool) {
	if o == nil || o.Views == nil {
		return nil, false
	}
	return o.Views, true
}

// HasViews returns a boolean if a field has been set.
func (o *SmartsheetentityGetViewsResponse) HasViews() bool {
	if o != nil && o.Views != nil {
		return true
	}

	return false
}

// SetViews gets a reference to the given []SmartsheetentityView and assigns it to the Views field.
func (o *SmartsheetentityGetViewsResponse) SetViews(v []SmartsheetentityView) {
	o.Views = v
}

func (o SmartsheetentityGetViewsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.HasMore != nil {
		toSerialize["hasMore"] = o.HasMore
	}
	if o.Next != nil {
		toSerialize["next"] = o.Next
	}
	if o.Views != nil {
		toSerialize["views"] = o.Views
	}
	return json.Marshal(toSerialize)
}

type NullableSmartsheetentityGetViewsResponse struct {
	value *SmartsheetentityGetViewsResponse
	isSet bool
}

func (v NullableSmartsheetentityGetViewsResponse) Get() *SmartsheetentityGetViewsResponse {
	return v.value
}

func (v *NullableSmartsheetentityGetViewsResponse) Set(val *SmartsheetentityGetViewsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartsheetentityGetViewsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartsheetentityGetViewsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartsheetentityGetViewsResponse(val *SmartsheetentityGetViewsResponse) *NullableSmartsheetentityGetViewsResponse {
	return &NullableSmartsheetentityGetViewsResponse{value: val, isSet: true}
}

func (v NullableSmartsheetentityGetViewsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartsheetentityGetViewsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


