/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ViewResource struct for ViewResource
type ViewResource struct {
	ViewID *string `json:"viewID,omitempty"`
	ViewTitle *string `json:"viewTitle,omitempty"`
	ViewType *int32 `json:"viewType,omitempty"`
}

// NewViewResource instantiates a new ViewResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewResource() *ViewResource {
	this := ViewResource{}
	return &this
}

// NewViewResourceWithDefaults instantiates a new ViewResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewResourceWithDefaults() *ViewResource {
	this := ViewResource{}
	return &this
}

// GetViewID returns the ViewID field value if set, zero value otherwise.
func (o *ViewResource) GetViewID() string {
	if o == nil || o.ViewID == nil {
		var ret string
		return ret
	}
	return *o.ViewID
}

// GetViewIDOk returns a tuple with the ViewID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewResource) GetViewIDOk() (*string, bool) {
	if o == nil || o.ViewID == nil {
		return nil, false
	}
	return o.ViewID, true
}

// HasViewID returns a boolean if a field has been set.
func (o *ViewResource) HasViewID() bool {
	if o != nil && o.ViewID != nil {
		return true
	}

	return false
}

// SetViewID gets a reference to the given string and assigns it to the ViewID field.
func (o *ViewResource) SetViewID(v string) {
	o.ViewID = &v
}

// GetViewTitle returns the ViewTitle field value if set, zero value otherwise.
func (o *ViewResource) GetViewTitle() string {
	if o == nil || o.ViewTitle == nil {
		var ret string
		return ret
	}
	return *o.ViewTitle
}

// GetViewTitleOk returns a tuple with the ViewTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewResource) GetViewTitleOk() (*string, bool) {
	if o == nil || o.ViewTitle == nil {
		return nil, false
	}
	return o.ViewTitle, true
}

// HasViewTitle returns a boolean if a field has been set.
func (o *ViewResource) HasViewTitle() bool {
	if o != nil && o.ViewTitle != nil {
		return true
	}

	return false
}

// SetViewTitle gets a reference to the given string and assigns it to the ViewTitle field.
func (o *ViewResource) SetViewTitle(v string) {
	o.ViewTitle = &v
}

// GetViewType returns the ViewType field value if set, zero value otherwise.
func (o *ViewResource) GetViewType() int32 {
	if o == nil || o.ViewType == nil {
		var ret int32
		return ret
	}
	return *o.ViewType
}

// GetViewTypeOk returns a tuple with the ViewType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewResource) GetViewTypeOk() (*int32, bool) {
	if o == nil || o.ViewType == nil {
		return nil, false
	}
	return o.ViewType, true
}

// HasViewType returns a boolean if a field has been set.
func (o *ViewResource) HasViewType() bool {
	if o != nil && o.ViewType != nil {
		return true
	}

	return false
}

// SetViewType gets a reference to the given int32 and assigns it to the ViewType field.
func (o *ViewResource) SetViewType(v int32) {
	o.ViewType = &v
}

func (o ViewResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ViewID != nil {
		toSerialize["viewID"] = o.ViewID
	}
	if o.ViewTitle != nil {
		toSerialize["viewTitle"] = o.ViewTitle
	}
	if o.ViewType != nil {
		toSerialize["viewType"] = o.ViewType
	}
	return json.Marshal(toSerialize)
}

type NullableViewResource struct {
	value *ViewResource
	isSet bool
}

func (v NullableViewResource) Get() *ViewResource {
	return v.value
}

func (v *NullableViewResource) Set(val *ViewResource) {
	v.value = val
	v.isSet = true
}

func (v NullableViewResource) IsSet() bool {
	return v.isSet
}

func (v *NullableViewResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewResource(val *ViewResource) *NullableViewResource {
	return &NullableViewResource{value: val, isSet: true}
}

func (v NullableViewResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


