/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OAuthAPIResponse1 struct for OAuthAPIResponse1
type OAuthAPIResponse1 struct {
	Ret *int32 `json:"ret,omitempty"`
	Msg *string `json:"msg,omitempty"`
	Data *GetTokenRsp `json:"data,omitempty"`
}

// NewOAuthAPIResponse1 instantiates a new OAuthAPIResponse1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthAPIResponse1() *OAuthAPIResponse1 {
	this := OAuthAPIResponse1{}
	return &this
}

// NewOAuthAPIResponse1WithDefaults instantiates a new OAuthAPIResponse1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthAPIResponse1WithDefaults() *OAuthAPIResponse1 {
	this := OAuthAPIResponse1{}
	return &this
}

// GetRet returns the Ret field value if set, zero value otherwise.
func (o *OAuthAPIResponse1) GetRet() int32 {
	if o == nil || o.Ret == nil {
		var ret int32
		return ret
	}
	return *o.Ret
}

// GetRetOk returns a tuple with the Ret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthAPIResponse1) GetRetOk() (*int32, bool) {
	if o == nil || o.Ret == nil {
		return nil, false
	}
	return o.Ret, true
}

// HasRet returns a boolean if a field has been set.
func (o *OAuthAPIResponse1) HasRet() bool {
	if o != nil && o.Ret != nil {
		return true
	}

	return false
}

// SetRet gets a reference to the given int32 and assigns it to the Ret field.
func (o *OAuthAPIResponse1) SetRet(v int32) {
	o.Ret = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *OAuthAPIResponse1) GetMsg() string {
	if o == nil || o.Msg == nil {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthAPIResponse1) GetMsgOk() (*string, bool) {
	if o == nil || o.Msg == nil {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *OAuthAPIResponse1) HasMsg() bool {
	if o != nil && o.Msg != nil {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *OAuthAPIResponse1) SetMsg(v string) {
	o.Msg = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OAuthAPIResponse1) GetData() GetTokenRsp {
	if o == nil || o.Data == nil {
		var ret GetTokenRsp
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthAPIResponse1) GetDataOk() (*GetTokenRsp, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OAuthAPIResponse1) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetTokenRsp and assigns it to the Data field.
func (o *OAuthAPIResponse1) SetData(v GetTokenRsp) {
	o.Data = &v
}

func (o OAuthAPIResponse1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Ret != nil {
		toSerialize["ret"] = o.Ret
	}
	if o.Msg != nil {
		toSerialize["msg"] = o.Msg
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableOAuthAPIResponse1 struct {
	value *OAuthAPIResponse1
	isSet bool
}

func (v NullableOAuthAPIResponse1) Get() *OAuthAPIResponse1 {
	return v.value
}

func (v *NullableOAuthAPIResponse1) Set(val *OAuthAPIResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthAPIResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthAPIResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthAPIResponse1(val *OAuthAPIResponse1) *NullableOAuthAPIResponse1 {
	return &NullableOAuthAPIResponse1{value: val, isSet: true}
}

func (v NullableOAuthAPIResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthAPIResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


