/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmartsheetentityAddViewRequest 新建视图请求，创建一个视图
type SmartsheetentityAddViewRequest struct {
	ViewTitle *string `json:"viewTitle,omitempty"`
	ViewType *string `json:"viewType,omitempty"`
}

// NewSmartsheetentityAddViewRequest instantiates a new SmartsheetentityAddViewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartsheetentityAddViewRequest() *SmartsheetentityAddViewRequest {
	this := SmartsheetentityAddViewRequest{}
	return &this
}

// NewSmartsheetentityAddViewRequestWithDefaults instantiates a new SmartsheetentityAddViewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartsheetentityAddViewRequestWithDefaults() *SmartsheetentityAddViewRequest {
	this := SmartsheetentityAddViewRequest{}
	return &this
}

// GetViewTitle returns the ViewTitle field value if set, zero value otherwise.
func (o *SmartsheetentityAddViewRequest) GetViewTitle() string {
	if o == nil || o.ViewTitle == nil {
		var ret string
		return ret
	}
	return *o.ViewTitle
}

// GetViewTitleOk returns a tuple with the ViewTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityAddViewRequest) GetViewTitleOk() (*string, bool) {
	if o == nil || o.ViewTitle == nil {
		return nil, false
	}
	return o.ViewTitle, true
}

// HasViewTitle returns a boolean if a field has been set.
func (o *SmartsheetentityAddViewRequest) HasViewTitle() bool {
	if o != nil && o.ViewTitle != nil {
		return true
	}

	return false
}

// SetViewTitle gets a reference to the given string and assigns it to the ViewTitle field.
func (o *SmartsheetentityAddViewRequest) SetViewTitle(v string) {
	o.ViewTitle = &v
}

// GetViewType returns the ViewType field value if set, zero value otherwise.
func (o *SmartsheetentityAddViewRequest) GetViewType() string {
	if o == nil || o.ViewType == nil {
		var ret string
		return ret
	}
	return *o.ViewType
}

// GetViewTypeOk returns a tuple with the ViewType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityAddViewRequest) GetViewTypeOk() (*string, bool) {
	if o == nil || o.ViewType == nil {
		return nil, false
	}
	return o.ViewType, true
}

// HasViewType returns a boolean if a field has been set.
func (o *SmartsheetentityAddViewRequest) HasViewType() bool {
	if o != nil && o.ViewType != nil {
		return true
	}

	return false
}

// SetViewType gets a reference to the given string and assigns it to the ViewType field.
func (o *SmartsheetentityAddViewRequest) SetViewType(v string) {
	o.ViewType = &v
}

func (o SmartsheetentityAddViewRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ViewTitle != nil {
		toSerialize["viewTitle"] = o.ViewTitle
	}
	if o.ViewType != nil {
		toSerialize["viewType"] = o.ViewType
	}
	return json.Marshal(toSerialize)
}

type NullableSmartsheetentityAddViewRequest struct {
	value *SmartsheetentityAddViewRequest
	isSet bool
}

func (v NullableSmartsheetentityAddViewRequest) Get() *SmartsheetentityAddViewRequest {
	return v.value
}

func (v *NullableSmartsheetentityAddViewRequest) Set(val *SmartsheetentityAddViewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartsheetentityAddViewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartsheetentityAddViewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartsheetentityAddViewRequest(val *SmartsheetentityAddViewRequest) *NullableSmartsheetentityAddViewRequest {
	return &NullableSmartsheetentityAddViewRequest{value: val, isSet: true}
}

func (v NullableSmartsheetentityAddViewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartsheetentityAddViewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


