/*
 * Tencent Docs SDK
 *
 * This is tencent docs editorapi sdk
 *
 * API version: 0.1.0
 * Contact: tencentdocs@tencent.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Request struct {
	InsertText     *InsertTextRequest     `json:"insertText,omitempty"`
	InsertImage    *InsertImageRequest    `json:"insertImage,omitempty"`
	InsertWebBlock *InsertWebBlockRequest `json:"insertWebBlock,omitempty"`
}
