/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateRecordsResponse 更新指定表格和子表中的一到多条记录回包
type UpdateRecordsResponse struct {
	Records []CommonRecord `json:"records,omitempty"`
}

// NewUpdateRecordsResponse instantiates a new UpdateRecordsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRecordsResponse() *UpdateRecordsResponse {
	this := UpdateRecordsResponse{}
	return &this
}

// NewUpdateRecordsResponseWithDefaults instantiates a new UpdateRecordsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRecordsResponseWithDefaults() *UpdateRecordsResponse {
	this := UpdateRecordsResponse{}
	return &this
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *UpdateRecordsResponse) GetRecords() []CommonRecord {
	if o == nil || o.Records == nil {
		var ret []CommonRecord
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRecordsResponse) GetRecordsOk() ([]CommonRecord, bool) {
	if o == nil || o.Records == nil {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *UpdateRecordsResponse) HasRecords() bool {
	if o != nil && o.Records != nil {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []CommonRecord and assigns it to the Records field.
func (o *UpdateRecordsResponse) SetRecords(v []CommonRecord) {
	o.Records = v
}

func (o UpdateRecordsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Records != nil {
		toSerialize["records"] = o.Records
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateRecordsResponse struct {
	value *UpdateRecordsResponse
	isSet bool
}

func (v NullableUpdateRecordsResponse) Get() *UpdateRecordsResponse {
	return v.value
}

func (v *NullableUpdateRecordsResponse) Set(val *UpdateRecordsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRecordsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRecordsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRecordsResponse(val *UpdateRecordsResponse) *NullableUpdateRecordsResponse {
	return &NullableUpdateRecordsResponse{value: val, isSet: true}
}

func (v NullableUpdateRecordsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRecordsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


