/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddRecordsResponse 在指定表格和子表中创建一到多条新记录回包
type AddRecordsResponse struct {
	Records []CommonRecord `json:"records,omitempty"`
}

// NewAddRecordsResponse instantiates a new AddRecordsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddRecordsResponse() *AddRecordsResponse {
	this := AddRecordsResponse{}
	return &this
}

// NewAddRecordsResponseWithDefaults instantiates a new AddRecordsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddRecordsResponseWithDefaults() *AddRecordsResponse {
	this := AddRecordsResponse{}
	return &this
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *AddRecordsResponse) GetRecords() []CommonRecord {
	if o == nil || o.Records == nil {
		var ret []CommonRecord
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddRecordsResponse) GetRecordsOk() ([]CommonRecord, bool) {
	if o == nil || o.Records == nil {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *AddRecordsResponse) HasRecords() bool {
	if o != nil && o.Records != nil {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []CommonRecord and assigns it to the Records field.
func (o *AddRecordsResponse) SetRecords(v []CommonRecord) {
	o.Records = v
}

func (o AddRecordsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Records != nil {
		toSerialize["records"] = o.Records
	}
	return json.Marshal(toSerialize)
}

type NullableAddRecordsResponse struct {
	value *AddRecordsResponse
	isSet bool
}

func (v NullableAddRecordsResponse) Get() *AddRecordsResponse {
	return v.value
}

func (v *NullableAddRecordsResponse) Set(val *AddRecordsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddRecordsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddRecordsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddRecordsResponse(val *AddRecordsResponse) *NullableAddRecordsResponse {
	return &NullableAddRecordsResponse{value: val, isSet: true}
}

func (v NullableAddRecordsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddRecordsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


