/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CardConfig CardConfig 定义卡片配置
type CardConfig struct {
	Var1 *bool `json:"1,omitempty"`
	Var2 *string `json:"2,omitempty"`
	Var3 *int32 `json:"3,omitempty"`
	Var4 *bool `json:"4,omitempty"`
	Var5 *int32 `json:"5,omitempty"`
}

// NewCardConfig instantiates a new CardConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardConfig() *CardConfig {
	this := CardConfig{}
	return &this
}

// NewCardConfigWithDefaults instantiates a new CardConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardConfigWithDefaults() *CardConfig {
	this := CardConfig{}
	return &this
}

// GetVar1 returns the Var1 field value if set, zero value otherwise.
func (o *CardConfig) GetVar1() bool {
	if o == nil || o.Var1 == nil {
		var ret bool
		return ret
	}
	return *o.Var1
}

// GetVar1Ok returns a tuple with the Var1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardConfig) GetVar1Ok() (*bool, bool) {
	if o == nil || o.Var1 == nil {
		return nil, false
	}
	return o.Var1, true
}

// HasVar1 returns a boolean if a field has been set.
func (o *CardConfig) HasVar1() bool {
	if o != nil && o.Var1 != nil {
		return true
	}

	return false
}

// SetVar1 gets a reference to the given bool and assigns it to the Var1 field.
func (o *CardConfig) SetVar1(v bool) {
	o.Var1 = &v
}

// GetVar2 returns the Var2 field value if set, zero value otherwise.
func (o *CardConfig) GetVar2() string {
	if o == nil || o.Var2 == nil {
		var ret string
		return ret
	}
	return *o.Var2
}

// GetVar2Ok returns a tuple with the Var2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardConfig) GetVar2Ok() (*string, bool) {
	if o == nil || o.Var2 == nil {
		return nil, false
	}
	return o.Var2, true
}

// HasVar2 returns a boolean if a field has been set.
func (o *CardConfig) HasVar2() bool {
	if o != nil && o.Var2 != nil {
		return true
	}

	return false
}

// SetVar2 gets a reference to the given string and assigns it to the Var2 field.
func (o *CardConfig) SetVar2(v string) {
	o.Var2 = &v
}

// GetVar3 returns the Var3 field value if set, zero value otherwise.
func (o *CardConfig) GetVar3() int32 {
	if o == nil || o.Var3 == nil {
		var ret int32
		return ret
	}
	return *o.Var3
}

// GetVar3Ok returns a tuple with the Var3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardConfig) GetVar3Ok() (*int32, bool) {
	if o == nil || o.Var3 == nil {
		return nil, false
	}
	return o.Var3, true
}

// HasVar3 returns a boolean if a field has been set.
func (o *CardConfig) HasVar3() bool {
	if o != nil && o.Var3 != nil {
		return true
	}

	return false
}

// SetVar3 gets a reference to the given int32 and assigns it to the Var3 field.
func (o *CardConfig) SetVar3(v int32) {
	o.Var3 = &v
}

// GetVar4 returns the Var4 field value if set, zero value otherwise.
func (o *CardConfig) GetVar4() bool {
	if o == nil || o.Var4 == nil {
		var ret bool
		return ret
	}
	return *o.Var4
}

// GetVar4Ok returns a tuple with the Var4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardConfig) GetVar4Ok() (*bool, bool) {
	if o == nil || o.Var4 == nil {
		return nil, false
	}
	return o.Var4, true
}

// HasVar4 returns a boolean if a field has been set.
func (o *CardConfig) HasVar4() bool {
	if o != nil && o.Var4 != nil {
		return true
	}

	return false
}

// SetVar4 gets a reference to the given bool and assigns it to the Var4 field.
func (o *CardConfig) SetVar4(v bool) {
	o.Var4 = &v
}

// GetVar5 returns the Var5 field value if set, zero value otherwise.
func (o *CardConfig) GetVar5() int32 {
	if o == nil || o.Var5 == nil {
		var ret int32
		return ret
	}
	return *o.Var5
}

// GetVar5Ok returns a tuple with the Var5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardConfig) GetVar5Ok() (*int32, bool) {
	if o == nil || o.Var5 == nil {
		return nil, false
	}
	return o.Var5, true
}

// HasVar5 returns a boolean if a field has been set.
func (o *CardConfig) HasVar5() bool {
	if o != nil && o.Var5 != nil {
		return true
	}

	return false
}

// SetVar5 gets a reference to the given int32 and assigns it to the Var5 field.
func (o *CardConfig) SetVar5(v int32) {
	o.Var5 = &v
}

func (o CardConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Var1 != nil {
		toSerialize["1"] = o.Var1
	}
	if o.Var2 != nil {
		toSerialize["2"] = o.Var2
	}
	if o.Var3 != nil {
		toSerialize["3"] = o.Var3
	}
	if o.Var4 != nil {
		toSerialize["4"] = o.Var4
	}
	if o.Var5 != nil {
		toSerialize["5"] = o.Var5
	}
	return json.Marshal(toSerialize)
}

type NullableCardConfig struct {
	value *CardConfig
	isSet bool
}

func (v NullableCardConfig) Get() *CardConfig {
	return v.value
}

func (v *NullableCardConfig) Set(val *CardConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableCardConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableCardConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardConfig(val *CardConfig) *NullableCardConfig {
	return &NullableCardConfig{value: val, isSet: true}
}

func (v NullableCardConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


