/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ModifiedTimeFieldProperty struct for ModifiedTimeFieldProperty
type ModifiedTimeFieldProperty struct {
	Format *string `json:"format,omitempty"`
}

// NewModifiedTimeFieldProperty instantiates a new ModifiedTimeFieldProperty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifiedTimeFieldProperty() *ModifiedTimeFieldProperty {
	this := ModifiedTimeFieldProperty{}
	return &this
}

// NewModifiedTimeFieldPropertyWithDefaults instantiates a new ModifiedTimeFieldProperty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifiedTimeFieldPropertyWithDefaults() *ModifiedTimeFieldProperty {
	this := ModifiedTimeFieldProperty{}
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *ModifiedTimeFieldProperty) GetFormat() string {
	if o == nil || o.Format == nil {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifiedTimeFieldProperty) GetFormatOk() (*string, bool) {
	if o == nil || o.Format == nil {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *ModifiedTimeFieldProperty) HasFormat() bool {
	if o != nil && o.Format != nil {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *ModifiedTimeFieldProperty) SetFormat(v string) {
	o.Format = &v
}

func (o ModifiedTimeFieldProperty) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Format != nil {
		toSerialize["format"] = o.Format
	}
	return json.Marshal(toSerialize)
}

type NullableModifiedTimeFieldProperty struct {
	value *ModifiedTimeFieldProperty
	isSet bool
}

func (v NullableModifiedTimeFieldProperty) Get() *ModifiedTimeFieldProperty {
	return v.value
}

func (v *NullableModifiedTimeFieldProperty) Set(val *ModifiedTimeFieldProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableModifiedTimeFieldProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableModifiedTimeFieldProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifiedTimeFieldProperty(val *ModifiedTimeFieldProperty) *NullableModifiedTimeFieldProperty {
	return &NullableModifiedTimeFieldProperty{value: val, isSet: true}
}

func (v NullableModifiedTimeFieldProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifiedTimeFieldProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


