/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddFieldsRequest 新增字段请求
type AddFieldsRequest struct {
	Fields []AddField `json:"fields,omitempty"`
}

// NewAddFieldsRequest instantiates a new AddFieldsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddFieldsRequest() *AddFieldsRequest {
	this := AddFieldsRequest{}
	return &this
}

// NewAddFieldsRequestWithDefaults instantiates a new AddFieldsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddFieldsRequestWithDefaults() *AddFieldsRequest {
	this := AddFieldsRequest{}
	return &this
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *AddFieldsRequest) GetFields() []AddField {
	if o == nil || o.Fields == nil {
		var ret []AddField
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddFieldsRequest) GetFieldsOk() ([]AddField, bool) {
	if o == nil || o.Fields == nil {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *AddFieldsRequest) HasFields() bool {
	if o != nil && o.Fields != nil {
		return true
	}

	return false
}

// SetFields gets a reference to the given []AddField and assigns it to the Fields field.
func (o *AddFieldsRequest) SetFields(v []AddField) {
	o.Fields = v
}

func (o AddFieldsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	return json.Marshal(toSerialize)
}

type NullableAddFieldsRequest struct {
	value *AddFieldsRequest
	isSet bool
}

func (v NullableAddFieldsRequest) Get() *AddFieldsRequest {
	return v.value
}

func (v *NullableAddFieldsRequest) Set(val *AddFieldsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddFieldsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddFieldsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddFieldsRequest(val *AddFieldsRequest) *NullableAddFieldsRequest {
	return &NullableAddFieldsRequest{value: val, isSet: true}
}

func (v NullableAddFieldsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddFieldsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


