/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com/open/wiki); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GoogleProtobufStringValue Wrapper message for `string`. The JSON representation for `StringValue` is JSON string.
type GoogleProtobufStringValue struct {
	// The string value.
	Value *string `json:"value,omitempty"`
}

// NewGoogleProtobufStringValue instantiates a new GoogleProtobufStringValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleProtobufStringValue() *GoogleProtobufStringValue {
	this := GoogleProtobufStringValue{}
	return &this
}

// NewGoogleProtobufStringValueWithDefaults instantiates a new GoogleProtobufStringValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleProtobufStringValueWithDefaults() *GoogleProtobufStringValue {
	this := GoogleProtobufStringValue{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GoogleProtobufStringValue) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleProtobufStringValue) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GoogleProtobufStringValue) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *GoogleProtobufStringValue) SetValue(v string) {
	o.Value = &v
}

func (o GoogleProtobufStringValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableGoogleProtobufStringValue struct {
	value *GoogleProtobufStringValue
	isSet bool
}

func (v NullableGoogleProtobufStringValue) Get() *GoogleProtobufStringValue {
	return v.value
}

func (v *NullableGoogleProtobufStringValue) Set(val *GoogleProtobufStringValue) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleProtobufStringValue) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleProtobufStringValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleProtobufStringValue(val *GoogleProtobufStringValue) *NullableGoogleProtobufStringValue {
	return &NullableGoogleProtobufStringValue{value: val, isSet: true}
}

func (v NullableGoogleProtobufStringValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleProtobufStringValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


