/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Response1 struct for Response1
type Response1 struct {
	GetDocFullTextRsp *GetDocFullTextRsp `json:"getDocFullTextRsp,omitempty"`
}

// NewResponse1 instantiates a new Response1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponse1() *Response1 {
	this := Response1{}
	return &this
}

// NewResponse1WithDefaults instantiates a new Response1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponse1WithDefaults() *Response1 {
	this := Response1{}
	return &this
}

// GetGetDocFullTextRsp returns the GetDocFullTextRsp field value if set, zero value otherwise.
func (o *Response1) GetGetDocFullTextRsp() GetDocFullTextRsp {
	if o == nil || o.GetDocFullTextRsp == nil {
		var ret GetDocFullTextRsp
		return ret
	}
	return *o.GetDocFullTextRsp
}

// GetGetDocFullTextRspOk returns a tuple with the GetDocFullTextRsp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Response1) GetGetDocFullTextRspOk() (*GetDocFullTextRsp, bool) {
	if o == nil || o.GetDocFullTextRsp == nil {
		return nil, false
	}
	return o.GetDocFullTextRsp, true
}

// HasGetDocFullTextRsp returns a boolean if a field has been set.
func (o *Response1) HasGetDocFullTextRsp() bool {
	if o != nil && o.GetDocFullTextRsp != nil {
		return true
	}

	return false
}

// SetGetDocFullTextRsp gets a reference to the given GetDocFullTextRsp and assigns it to the GetDocFullTextRsp field.
func (o *Response1) SetGetDocFullTextRsp(v GetDocFullTextRsp) {
	o.GetDocFullTextRsp = &v
}

func (o Response1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GetDocFullTextRsp != nil {
		toSerialize["getDocFullTextRsp"] = o.GetDocFullTextRsp
	}
	return json.Marshal(toSerialize)
}

type NullableResponse1 struct {
	value *Response1
	isSet bool
}

func (v NullableResponse1) Get() *Response1 {
	return v.value
}

func (v *NullableResponse1) Set(val *Response1) {
	v.value = val
	v.isSet = true
}

func (v NullableResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponse1(val *Response1) *NullableResponse1 {
	return &NullableResponse1{value: val, isSet: true}
}

func (v NullableResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


