/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmartsheetentityGetViewsRequest 获取所有视图请求
type SmartsheetentityGetViewsRequest struct {
	ViewIDs []string `json:"viewIDs,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
}

// NewSmartsheetentityGetViewsRequest instantiates a new SmartsheetentityGetViewsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartsheetentityGetViewsRequest() *SmartsheetentityGetViewsRequest {
	this := SmartsheetentityGetViewsRequest{}
	return &this
}

// NewSmartsheetentityGetViewsRequestWithDefaults instantiates a new SmartsheetentityGetViewsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartsheetentityGetViewsRequestWithDefaults() *SmartsheetentityGetViewsRequest {
	this := SmartsheetentityGetViewsRequest{}
	return &this
}

// GetViewIDs returns the ViewIDs field value if set, zero value otherwise.
func (o *SmartsheetentityGetViewsRequest) GetViewIDs() []string {
	if o == nil || o.ViewIDs == nil {
		var ret []string
		return ret
	}
	return o.ViewIDs
}

// GetViewIDsOk returns a tuple with the ViewIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityGetViewsRequest) GetViewIDsOk() ([]string, bool) {
	if o == nil || o.ViewIDs == nil {
		return nil, false
	}
	return o.ViewIDs, true
}

// HasViewIDs returns a boolean if a field has been set.
func (o *SmartsheetentityGetViewsRequest) HasViewIDs() bool {
	if o != nil && o.ViewIDs != nil {
		return true
	}

	return false
}

// SetViewIDs gets a reference to the given []string and assigns it to the ViewIDs field.
func (o *SmartsheetentityGetViewsRequest) SetViewIDs(v []string) {
	o.ViewIDs = v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *SmartsheetentityGetViewsRequest) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityGetViewsRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *SmartsheetentityGetViewsRequest) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *SmartsheetentityGetViewsRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *SmartsheetentityGetViewsRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityGetViewsRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *SmartsheetentityGetViewsRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *SmartsheetentityGetViewsRequest) SetLimit(v int32) {
	o.Limit = &v
}

func (o SmartsheetentityGetViewsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ViewIDs != nil {
		toSerialize["viewIDs"] = o.ViewIDs
	}
	if o.Offset != nil {
		toSerialize["offset"] = o.Offset
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	return json.Marshal(toSerialize)
}

type NullableSmartsheetentityGetViewsRequest struct {
	value *SmartsheetentityGetViewsRequest
	isSet bool
}

func (v NullableSmartsheetentityGetViewsRequest) Get() *SmartsheetentityGetViewsRequest {
	return v.value
}

func (v *NullableSmartsheetentityGetViewsRequest) Set(val *SmartsheetentityGetViewsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartsheetentityGetViewsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartsheetentityGetViewsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartsheetentityGetViewsRequest(val *SmartsheetentityGetViewsRequest) *NullableSmartsheetentityGetViewsRequest {
	return &NullableSmartsheetentityGetViewsRequest{value: val, isSet: true}
}

func (v NullableSmartsheetentityGetViewsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartsheetentityGetViewsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


