/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StringValue Wrapper message for `string`. The JSON representation for `StringValue` is JSON string.
type StringValue struct {
	// The string value.
	Value *string `json:"value,omitempty"`
}

// NewStringValue instantiates a new StringValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStringValue() *StringValue {
	this := StringValue{}
	return &this
}

// NewStringValueWithDefaults instantiates a new StringValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStringValueWithDefaults() *StringValue {
	this := StringValue{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *StringValue) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StringValue) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *StringValue) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *StringValue) SetValue(v string) {
	o.Value = &v
}

func (o StringValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableStringValue struct {
	value *StringValue
	isSet bool
}

func (v NullableStringValue) Get() *StringValue {
	return v.value
}

func (v *NullableStringValue) Set(val *StringValue) {
	v.value = val
	v.isSet = true
}

func (v NullableStringValue) IsSet() bool {
	return v.isSet
}

func (v *NullableStringValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStringValue(val *StringValue) *NullableStringValue {
	return &NullableStringValue{value: val, isSet: true}
}

func (v NullableStringValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStringValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


