/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OAuthAPIResponse3 struct for OAuthAPIResponse3
type OAuthAPIResponse3 struct {
	Ret int32 `json:"ret"`
	Msg string `json:"msg"`
	Data *RefreshTokenRsp `json:"data,omitempty"`
}

// NewOAuthAPIResponse3 instantiates a new OAuthAPIResponse3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuthAPIResponse3(ret int32, msg string) *OAuthAPIResponse3 {
	this := OAuthAPIResponse3{}
	this.Ret = ret
	this.Msg = msg
	return &this
}

// NewOAuthAPIResponse3WithDefaults instantiates a new OAuthAPIResponse3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuthAPIResponse3WithDefaults() *OAuthAPIResponse3 {
	this := OAuthAPIResponse3{}
	return &this
}

// GetRet returns the Ret field value
func (o *OAuthAPIResponse3) GetRet() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ret
}

// GetRetOk returns a tuple with the Ret field value
// and a boolean to check if the value has been set.
func (o *OAuthAPIResponse3) GetRetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ret, true
}

// SetRet sets field value
func (o *OAuthAPIResponse3) SetRet(v int32) {
	o.Ret = v
}

// GetMsg returns the Msg field value
func (o *OAuthAPIResponse3) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *OAuthAPIResponse3) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *OAuthAPIResponse3) SetMsg(v string) {
	o.Msg = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OAuthAPIResponse3) GetData() RefreshTokenRsp {
	if o == nil || o.Data == nil {
		var ret RefreshTokenRsp
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuthAPIResponse3) GetDataOk() (*RefreshTokenRsp, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OAuthAPIResponse3) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given RefreshTokenRsp and assigns it to the Data field.
func (o *OAuthAPIResponse3) SetData(v RefreshTokenRsp) {
	o.Data = &v
}

func (o OAuthAPIResponse3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ret"] = o.Ret
	}
	if true {
		toSerialize["msg"] = o.Msg
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableOAuthAPIResponse3 struct {
	value *OAuthAPIResponse3
	isSet bool
}

func (v NullableOAuthAPIResponse3) Get() *OAuthAPIResponse3 {
	return v.value
}

func (v *NullableOAuthAPIResponse3) Set(val *OAuthAPIResponse3) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuthAPIResponse3) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuthAPIResponse3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuthAPIResponse3(val *OAuthAPIResponse3) *NullableOAuthAPIResponse3 {
	return &NullableOAuthAPIResponse3{value: val, isSet: true}
}

func (v NullableOAuthAPIResponse3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuthAPIResponse3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


