/*
 * Tencent Docs SDK
 *
 * This is tencent docs editorapi sdk
 *
 * API version: 0.1.0
 * Contact: tencentdocs@tencent.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InsertImageRequest struct {
	// 图片 ID
	ImageID string `json:"imageID"`
	Location *Location `json:"location"`
	// 图片宽度, 单位为 emu
	Width int32 `json:"width,omitempty"`
	// 图片高度, 单位为 emu
	Height int32 `json:"height,omitempty"`
	// 业务来源
	AddonSource int32 `json:"addonSource,omitempty"`
	// 插件ID
	AddonID string `json:"addonID,omitempty"`
	// 文档插件元素的唯一 ID (6位的数字小写字母组合)
	AnchorID string `json:"anchorID,omitempty"`
	// 插件扩展字段
	ExtraData string `json:"extraData,omitempty"`
}
