/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmartsheetentityAddRecord struct for SmartsheetentityAddRecord
type SmartsheetentityAddRecord struct {
	Values *map[string]interface{} `json:"values,omitempty"`
}

// NewSmartsheetentityAddRecord instantiates a new SmartsheetentityAddRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartsheetentityAddRecord() *SmartsheetentityAddRecord {
	this := SmartsheetentityAddRecord{}
	return &this
}

// NewSmartsheetentityAddRecordWithDefaults instantiates a new SmartsheetentityAddRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartsheetentityAddRecordWithDefaults() *SmartsheetentityAddRecord {
	this := SmartsheetentityAddRecord{}
	return &this
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *SmartsheetentityAddRecord) GetValues() map[string]interface{} {
	if o == nil || o.Values == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetentityAddRecord) GetValuesOk() (*map[string]interface{}, bool) {
	if o == nil || o.Values == nil {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *SmartsheetentityAddRecord) HasValues() bool {
	if o != nil && o.Values != nil {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]interface{} and assigns it to the Values field.
func (o *SmartsheetentityAddRecord) SetValues(v map[string]interface{}) {
	o.Values = &v
}

func (o SmartsheetentityAddRecord) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Values != nil {
		toSerialize["values"] = o.Values
	}
	return json.Marshal(toSerialize)
}

type NullableSmartsheetentityAddRecord struct {
	value *SmartsheetentityAddRecord
	isSet bool
}

func (v NullableSmartsheetentityAddRecord) Get() *SmartsheetentityAddRecord {
	return v.value
}

func (v *NullableSmartsheetentityAddRecord) Set(val *SmartsheetentityAddRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartsheetentityAddRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartsheetentityAddRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartsheetentityAddRecord(val *SmartsheetentityAddRecord) *NullableSmartsheetentityAddRecord {
	return &NullableSmartsheetentityAddRecord{value: val, isSet: true}
}

func (v NullableSmartsheetentityAddRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartsheetentityAddRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


