/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// FileInfo struct for FileInfo
type FileInfo struct {
	Id *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Type *string `json:"type,omitempty"`
	Url *string `json:"url,omitempty"`
	Status *string `json:"status,omitempty"`
	IsCreator *bool `json:"isCreator,omitempty"`
	CreateTime *int32 `json:"createTime,omitempty"`
	CreatorName *string `json:"creatorName,omitempty"`
	IsOwner *bool `json:"isOwner,omitempty"`
	OwnerName *string `json:"ownerName,omitempty"`
	LastModifyTime *int32 `json:"lastModifyTime,omitempty"`
	LastModifyName *string `json:"lastModifyName,omitempty"`
	RelativeFiles []RelativeFiles `json:"relativeFiles,omitempty"`
	FormCollectingStatus *string `json:"formCollectingStatus,omitempty"`
	FormCollectingEndTime *int64 `json:"formCollectingEndTime,omitempty"`
}

// NewFileInfo instantiates a new FileInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileInfo() *FileInfo {
	this := FileInfo{}
	return &this
}

// NewFileInfoWithDefaults instantiates a new FileInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileInfoWithDefaults() *FileInfo {
	this := FileInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FileInfo) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FileInfo) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FileInfo) SetId(v string) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *FileInfo) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *FileInfo) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *FileInfo) SetTitle(v string) {
	o.Title = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FileInfo) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FileInfo) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FileInfo) SetType(v string) {
	o.Type = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *FileInfo) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *FileInfo) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *FileInfo) SetUrl(v string) {
	o.Url = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FileInfo) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FileInfo) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *FileInfo) SetStatus(v string) {
	o.Status = &v
}

// GetIsCreator returns the IsCreator field value if set, zero value otherwise.
func (o *FileInfo) GetIsCreator() bool {
	if o == nil || o.IsCreator == nil {
		var ret bool
		return ret
	}
	return *o.IsCreator
}

// GetIsCreatorOk returns a tuple with the IsCreator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetIsCreatorOk() (*bool, bool) {
	if o == nil || o.IsCreator == nil {
		return nil, false
	}
	return o.IsCreator, true
}

// HasIsCreator returns a boolean if a field has been set.
func (o *FileInfo) HasIsCreator() bool {
	if o != nil && o.IsCreator != nil {
		return true
	}

	return false
}

// SetIsCreator gets a reference to the given bool and assigns it to the IsCreator field.
func (o *FileInfo) SetIsCreator(v bool) {
	o.IsCreator = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *FileInfo) GetCreateTime() int32 {
	if o == nil || o.CreateTime == nil {
		var ret int32
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetCreateTimeOk() (*int32, bool) {
	if o == nil || o.CreateTime == nil {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *FileInfo) HasCreateTime() bool {
	if o != nil && o.CreateTime != nil {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given int32 and assigns it to the CreateTime field.
func (o *FileInfo) SetCreateTime(v int32) {
	o.CreateTime = &v
}

// GetCreatorName returns the CreatorName field value if set, zero value otherwise.
func (o *FileInfo) GetCreatorName() string {
	if o == nil || o.CreatorName == nil {
		var ret string
		return ret
	}
	return *o.CreatorName
}

// GetCreatorNameOk returns a tuple with the CreatorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetCreatorNameOk() (*string, bool) {
	if o == nil || o.CreatorName == nil {
		return nil, false
	}
	return o.CreatorName, true
}

// HasCreatorName returns a boolean if a field has been set.
func (o *FileInfo) HasCreatorName() bool {
	if o != nil && o.CreatorName != nil {
		return true
	}

	return false
}

// SetCreatorName gets a reference to the given string and assigns it to the CreatorName field.
func (o *FileInfo) SetCreatorName(v string) {
	o.CreatorName = &v
}

// GetIsOwner returns the IsOwner field value if set, zero value otherwise.
func (o *FileInfo) GetIsOwner() bool {
	if o == nil || o.IsOwner == nil {
		var ret bool
		return ret
	}
	return *o.IsOwner
}

// GetIsOwnerOk returns a tuple with the IsOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetIsOwnerOk() (*bool, bool) {
	if o == nil || o.IsOwner == nil {
		return nil, false
	}
	return o.IsOwner, true
}

// HasIsOwner returns a boolean if a field has been set.
func (o *FileInfo) HasIsOwner() bool {
	if o != nil && o.IsOwner != nil {
		return true
	}

	return false
}

// SetIsOwner gets a reference to the given bool and assigns it to the IsOwner field.
func (o *FileInfo) SetIsOwner(v bool) {
	o.IsOwner = &v
}

// GetOwnerName returns the OwnerName field value if set, zero value otherwise.
func (o *FileInfo) GetOwnerName() string {
	if o == nil || o.OwnerName == nil {
		var ret string
		return ret
	}
	return *o.OwnerName
}

// GetOwnerNameOk returns a tuple with the OwnerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetOwnerNameOk() (*string, bool) {
	if o == nil || o.OwnerName == nil {
		return nil, false
	}
	return o.OwnerName, true
}

// HasOwnerName returns a boolean if a field has been set.
func (o *FileInfo) HasOwnerName() bool {
	if o != nil && o.OwnerName != nil {
		return true
	}

	return false
}

// SetOwnerName gets a reference to the given string and assigns it to the OwnerName field.
func (o *FileInfo) SetOwnerName(v string) {
	o.OwnerName = &v
}

// GetLastModifyTime returns the LastModifyTime field value if set, zero value otherwise.
func (o *FileInfo) GetLastModifyTime() int32 {
	if o == nil || o.LastModifyTime == nil {
		var ret int32
		return ret
	}
	return *o.LastModifyTime
}

// GetLastModifyTimeOk returns a tuple with the LastModifyTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetLastModifyTimeOk() (*int32, bool) {
	if o == nil || o.LastModifyTime == nil {
		return nil, false
	}
	return o.LastModifyTime, true
}

// HasLastModifyTime returns a boolean if a field has been set.
func (o *FileInfo) HasLastModifyTime() bool {
	if o != nil && o.LastModifyTime != nil {
		return true
	}

	return false
}

// SetLastModifyTime gets a reference to the given int32 and assigns it to the LastModifyTime field.
func (o *FileInfo) SetLastModifyTime(v int32) {
	o.LastModifyTime = &v
}

// GetLastModifyName returns the LastModifyName field value if set, zero value otherwise.
func (o *FileInfo) GetLastModifyName() string {
	if o == nil || o.LastModifyName == nil {
		var ret string
		return ret
	}
	return *o.LastModifyName
}

// GetLastModifyNameOk returns a tuple with the LastModifyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetLastModifyNameOk() (*string, bool) {
	if o == nil || o.LastModifyName == nil {
		return nil, false
	}
	return o.LastModifyName, true
}

// HasLastModifyName returns a boolean if a field has been set.
func (o *FileInfo) HasLastModifyName() bool {
	if o != nil && o.LastModifyName != nil {
		return true
	}

	return false
}

// SetLastModifyName gets a reference to the given string and assigns it to the LastModifyName field.
func (o *FileInfo) SetLastModifyName(v string) {
	o.LastModifyName = &v
}

// GetRelativeFiles returns the RelativeFiles field value if set, zero value otherwise.
func (o *FileInfo) GetRelativeFiles() []RelativeFiles {
	if o == nil || o.RelativeFiles == nil {
		var ret []RelativeFiles
		return ret
	}
	return o.RelativeFiles
}

// GetRelativeFilesOk returns a tuple with the RelativeFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetRelativeFilesOk() ([]RelativeFiles, bool) {
	if o == nil || o.RelativeFiles == nil {
		return nil, false
	}
	return o.RelativeFiles, true
}

// HasRelativeFiles returns a boolean if a field has been set.
func (o *FileInfo) HasRelativeFiles() bool {
	if o != nil && o.RelativeFiles != nil {
		return true
	}

	return false
}

// SetRelativeFiles gets a reference to the given []RelativeFiles and assigns it to the RelativeFiles field.
func (o *FileInfo) SetRelativeFiles(v []RelativeFiles) {
	o.RelativeFiles = v
}

// GetFormCollectingStatus returns the FormCollectingStatus field value if set, zero value otherwise.
func (o *FileInfo) GetFormCollectingStatus() string {
	if o == nil || o.FormCollectingStatus == nil {
		var ret string
		return ret
	}
	return *o.FormCollectingStatus
}

// GetFormCollectingStatusOk returns a tuple with the FormCollectingStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetFormCollectingStatusOk() (*string, bool) {
	if o == nil || o.FormCollectingStatus == nil {
		return nil, false
	}
	return o.FormCollectingStatus, true
}

// HasFormCollectingStatus returns a boolean if a field has been set.
func (o *FileInfo) HasFormCollectingStatus() bool {
	if o != nil && o.FormCollectingStatus != nil {
		return true
	}

	return false
}

// SetFormCollectingStatus gets a reference to the given string and assigns it to the FormCollectingStatus field.
func (o *FileInfo) SetFormCollectingStatus(v string) {
	o.FormCollectingStatus = &v
}

// GetFormCollectingEndTime returns the FormCollectingEndTime field value if set, zero value otherwise.
func (o *FileInfo) GetFormCollectingEndTime() int64 {
	if o == nil || o.FormCollectingEndTime == nil {
		var ret int64
		return ret
	}
	return *o.FormCollectingEndTime
}

// GetFormCollectingEndTimeOk returns a tuple with the FormCollectingEndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetFormCollectingEndTimeOk() (*int64, bool) {
	if o == nil || o.FormCollectingEndTime == nil {
		return nil, false
	}
	return o.FormCollectingEndTime, true
}

// HasFormCollectingEndTime returns a boolean if a field has been set.
func (o *FileInfo) HasFormCollectingEndTime() bool {
	if o != nil && o.FormCollectingEndTime != nil {
		return true
	}

	return false
}

// SetFormCollectingEndTime gets a reference to the given int64 and assigns it to the FormCollectingEndTime field.
func (o *FileInfo) SetFormCollectingEndTime(v int64) {
	o.FormCollectingEndTime = &v
}

func (o FileInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.IsCreator != nil {
		toSerialize["isCreator"] = o.IsCreator
	}
	if o.CreateTime != nil {
		toSerialize["createTime"] = o.CreateTime
	}
	if o.CreatorName != nil {
		toSerialize["creatorName"] = o.CreatorName
	}
	if o.IsOwner != nil {
		toSerialize["isOwner"] = o.IsOwner
	}
	if o.OwnerName != nil {
		toSerialize["ownerName"] = o.OwnerName
	}
	if o.LastModifyTime != nil {
		toSerialize["lastModifyTime"] = o.LastModifyTime
	}
	if o.LastModifyName != nil {
		toSerialize["lastModifyName"] = o.LastModifyName
	}
	if o.RelativeFiles != nil {
		toSerialize["relativeFiles"] = o.RelativeFiles
	}
	if o.FormCollectingStatus != nil {
		toSerialize["formCollectingStatus"] = o.FormCollectingStatus
	}
	if o.FormCollectingEndTime != nil {
		toSerialize["formCollectingEndTime"] = o.FormCollectingEndTime
	}
	return json.Marshal(toSerialize)
}

type NullableFileInfo struct {
	value *FileInfo
	isSet bool
}

func (v NullableFileInfo) Get() *FileInfo {
	return v.value
}

func (v *NullableFileInfo) Set(val *FileInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFileInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFileInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileInfo(val *FileInfo) *NullableFileInfo {
	return &NullableFileInfo{value: val, isSet: true}
}

func (v NullableFileInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


