/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SmartsheetAddFieldsResponse 新增字段回包
type SmartsheetAddFieldsResponse struct {
	Fields []SmartsheetField `json:"fields,omitempty"`
}

// NewSmartsheetAddFieldsResponse instantiates a new SmartsheetAddFieldsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartsheetAddFieldsResponse() *SmartsheetAddFieldsResponse {
	this := SmartsheetAddFieldsResponse{}
	return &this
}

// NewSmartsheetAddFieldsResponseWithDefaults instantiates a new SmartsheetAddFieldsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartsheetAddFieldsResponseWithDefaults() *SmartsheetAddFieldsResponse {
	this := SmartsheetAddFieldsResponse{}
	return &this
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *SmartsheetAddFieldsResponse) GetFields() []SmartsheetField {
	if o == nil || o.Fields == nil {
		var ret []SmartsheetField
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartsheetAddFieldsResponse) GetFieldsOk() ([]SmartsheetField, bool) {
	if o == nil || o.Fields == nil {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *SmartsheetAddFieldsResponse) HasFields() bool {
	if o != nil && o.Fields != nil {
		return true
	}

	return false
}

// SetFields gets a reference to the given []SmartsheetField and assigns it to the Fields field.
func (o *SmartsheetAddFieldsResponse) SetFields(v []SmartsheetField) {
	o.Fields = v
}

func (o SmartsheetAddFieldsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	return json.Marshal(toSerialize)
}

type NullableSmartsheetAddFieldsResponse struct {
	value *SmartsheetAddFieldsResponse
	isSet bool
}

func (v NullableSmartsheetAddFieldsResponse) Get() *SmartsheetAddFieldsResponse {
	return v.value
}

func (v *NullableSmartsheetAddFieldsResponse) Set(val *SmartsheetAddFieldsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartsheetAddFieldsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartsheetAddFieldsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartsheetAddFieldsResponse(val *SmartsheetAddFieldsResponse) *NullableSmartsheetAddFieldsResponse {
	return &NullableSmartsheetAddFieldsResponse{value: val, isSet: true}
}

func (v NullableSmartsheetAddFieldsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartsheetAddFieldsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


