/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OpenResponse6 struct for OpenResponse6
type OpenResponse6 struct {
	Ret int32 `json:"ret"`
	Msg string `json:"msg"`
	Data *GetSubSheetResponse `json:"data,omitempty"`
}

// NewOpenResponse6 instantiates a new OpenResponse6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenResponse6(ret int32, msg string) *OpenResponse6 {
	this := OpenResponse6{}
	this.Ret = ret
	this.Msg = msg
	return &this
}

// NewOpenResponse6WithDefaults instantiates a new OpenResponse6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenResponse6WithDefaults() *OpenResponse6 {
	this := OpenResponse6{}
	return &this
}

// GetRet returns the Ret field value
func (o *OpenResponse6) GetRet() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ret
}

// GetRetOk returns a tuple with the Ret field value
// and a boolean to check if the value has been set.
func (o *OpenResponse6) GetRetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ret, true
}

// SetRet sets field value
func (o *OpenResponse6) SetRet(v int32) {
	o.Ret = v
}

// GetMsg returns the Msg field value
func (o *OpenResponse6) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *OpenResponse6) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *OpenResponse6) SetMsg(v string) {
	o.Msg = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *OpenResponse6) GetData() GetSubSheetResponse {
	if o == nil || o.Data == nil {
		var ret GetSubSheetResponse
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenResponse6) GetDataOk() (*GetSubSheetResponse, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *OpenResponse6) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetSubSheetResponse and assigns it to the Data field.
func (o *OpenResponse6) SetData(v GetSubSheetResponse) {
	o.Data = &v
}

func (o OpenResponse6) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ret"] = o.Ret
	}
	if true {
		toSerialize["msg"] = o.Msg
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableOpenResponse6 struct {
	value *OpenResponse6
	isSet bool
}

func (v NullableOpenResponse6) Get() *OpenResponse6 {
	return v.value
}

func (v *NullableOpenResponse6) Set(val *OpenResponse6) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenResponse6) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenResponse6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenResponse6(val *OpenResponse6) *NullableOpenResponse6 {
	return &NullableOpenResponse6{value: val, isSet: true}
}

func (v NullableOpenResponse6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenResponse6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


