/*
Tencent Docs SDK

Tencent docs sdk contains DocAPI, SmartsheetAPI, SheetAPI, DriveAPI and OAuthAPI

API version: 0.0.1
Contact: tencentdocs@tencent.com
*/

// Code generated by Tencent Docs (https://docs.qq.com); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateFieldsRequest 更新字段请求
type UpdateFieldsRequest struct {
	Fields []FieldResource `json:"fields,omitempty"`
}

// NewUpdateFieldsRequest instantiates a new UpdateFieldsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFieldsRequest() *UpdateFieldsRequest {
	this := UpdateFieldsRequest{}
	return &this
}

// NewUpdateFieldsRequestWithDefaults instantiates a new UpdateFieldsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFieldsRequestWithDefaults() *UpdateFieldsRequest {
	this := UpdateFieldsRequest{}
	return &this
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *UpdateFieldsRequest) GetFields() []FieldResource {
	if o == nil || o.Fields == nil {
		var ret []FieldResource
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFieldsRequest) GetFieldsOk() ([]FieldResource, bool) {
	if o == nil || o.Fields == nil {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *UpdateFieldsRequest) HasFields() bool {
	if o != nil && o.Fields != nil {
		return true
	}

	return false
}

// SetFields gets a reference to the given []FieldResource and assigns it to the Fields field.
func (o *UpdateFieldsRequest) SetFields(v []FieldResource) {
	o.Fields = v
}

func (o UpdateFieldsRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateFieldsRequest struct {
	value *UpdateFieldsRequest
	isSet bool
}

func (v NullableUpdateFieldsRequest) Get() *UpdateFieldsRequest {
	return v.value
}

func (v *NullableUpdateFieldsRequest) Set(val *UpdateFieldsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFieldsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFieldsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFieldsRequest(val *UpdateFieldsRequest) *NullableUpdateFieldsRequest {
	return &NullableUpdateFieldsRequest{value: val, isSet: true}
}

func (v NullableUpdateFieldsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFieldsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


